version: "3.7"

volumes:
  vault-data:

services:
  vault:
    image: "vault:latest"
    environment:
    - "VAULT_DEV_ROOT_TOKEN_ID=secret"
    - "VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200"
    ports:
    - "8200:8200"
    cap_add:
    - IPC_LOCK
    volumes:
    - "vault-data:/vault/file"
