FROM golang:latest AS build

ADD . /source
WORKDIR /source
RUN apt update && \
    apt install -y bash git make && \
    make build out=/source/vault-init

# ---
FROM debian:latest
LABEL maintainer="Sean Johnson <me@seanj.dev>"

COPY --from=build /source/vault-init /bin/vault-init

CMD ["vault-init"]