FROM golang:latest AS build

WORKDIR /source
ADD . /source/
RUN go install ./cmd/vault-init/...

# ---
FROM debian:latest
LABEL maintainer="Sean Johnson <me@seanj.dev>"

COPY --from=build /go/bin/vault-init /bin/vault-init

CMD ["vault-init"]