FROM golang:latest AS build

RUN go get -v glow.dev.maio.me/seanj/vault-init/cmd/vault-init

# ---
FROM debian:latest
LABEL maintainer="Sean Johnson <me@seanj.dev>"

COPY --from=build /go/bin/vault-init /bin/vault-init

CMD ["vault-init"]