---

resources:
- name: source
  type: git
  icon: git
  source:
    .: (( inject meta.repository.source ))

- name: alpine
  type: registry-image
  icon: docker
  source:
    repository: containers.dev.maio.me/library/alpine
    tag: latest

- name: debian
  type: registry-image
  icon: docker
  source:
    repository: debian
    tag: 9-slim

- name: vault-init-alpine
  type: registry-image
  icon: docker
  source:
    repository: (( grab meta.registry.image.repo ))
    tag: (( grab meta.registry.image.tag ))
    .: (( inject meta.registry.auth ))

- name: vault-init-debian
  type: registry-image
  icon: docker
  source:
    repository: (( grab meta.registry.image.repo ))
    tag: (( concat "debian-" meta.registry.image.tag ))
    .: (( inject meta.registry.auth ))

jobs:
- name: "go test"
  public: true
  plan:
  - get: source
    trigger: true
  - task: "run tests"
    file: (( grab meta.tasks.golang-test ))
    params:
      PACKAGE: glow.dev.maio.me/seanj/vault-init

- name: "go vet"
  public: true
  plan:
  - get: source
    trigger: true
  - task: "vet code"
    file: (( grab meta.tasks.golang-vet ))
    params:
      PACKAGE: glow.dev.maio.me/seanj/vault-init

- name: "build vault-init:alpine"
  public: true
  plan:
  - get: alpine
    trigger: true
  - get: source
    trigger: true
    passed:
    - "go test"
  - task: "build image"
    file: (( grab meta.tasks.img-build ))
    privileged: true
    params:
      REPOSITORY: (( grab meta.registry.image.repo ))
      TAG: (( grab meta.registry.image.tag || "latest" ))
      CONTEXT: (( grab meta.registry.image.context ))
      DOCKERFILE: (( concat meta.registry.image.context "Dockerfile" ))
  - put: vault-init-alpine
    params:
      image: image/image.tar

- name: "build vault-init:debian"
  public: true
  plan:
  - get: debian
    trigger: true
  - get: source
    trigger: true
    passed:
    - "go test"
  - task: "build image"
    file: (( grab meta.tasks.img-build ))
    privileged: true
    params:
      REPOSITORY: (( grab meta.registry.image.repo ))
      TAG: (( concat "debian-" meta.registry.image.tag ))
      CONTEXT: (( grab meta.registry.image.context ))
      DOCKERFILE: (( concat meta.registry.image.context "Dockerfile.debian" ))
  - put: vault-init-debian
    params:
      image: image/image.tar
