meta:
  target:   glow
  url:      https://concourse.dev.maio.me
  team:     main

  name:     vault-init
  pipeline: vault-init
  version:  v0.3.0

  registry:
    repository: containers.dev.maio.me
    auth:
      username: ((glow_registry_ci.username))
      password: ((glow_registry_ci.password))
    image:
      context: source/
      repo: (( concat meta.registry.repository "/pirogoeth/vault-init" ))
      tag: latest

  repository:
    source:
      uri: https://glow.dev.maio.me/seanj/vault-init.git
      branch: master

  tasks:
    golang-test: source/ci/tasks/golang/test.yml
    golang-vet: source/ci/tasks/golang/vet.yml
    img-build-oci: commons/tasks/img/build-oci.yml
    img-write-tags: commons/tasks/img/write-tags.yml

  upstream:
    alpine:
      repo: "containers.dev.maio.me/library/alpine"
      tag: "v3.10"
      auth:
        .: (( inject meta.registry.auth ))
    debian:
      repo: "debian"
      tag: "9-slim"
    commons:
      uri: "https://glow.dev.maio.me/containers/commons.git"
      branch: "master"
