---

platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: source

run:
  path: "/usr/local/go/bin/go"
  args: ["test", "-v"]
  dir: "./source"
